language: ruby
rvm:
  - 2.1.1

env:
  - DISPLAY=:99.0

before_script:
  - "cd spec/dummy"
  - "rake db:migrate"
  - "rake db:test:prepare"

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master
